trigger:
- main

variables:
  imageName: 'korupon/demo-app'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    goals: 'clean package'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'korupon/demo-app'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'myDockerRegistryServiceConnection'
    tags: 'latest'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'myAKSServiceConnection'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8s/deployment.yaml'
