trigger:
  branches:
    include:
      - main

stages:
- stage: DeployInfra
  jobs:
  - job: Terraform
    steps:
    - script: |
        terraform init
        terraform plan
        terraform apply -auto-approve
      displayName: 'Run Terraform'
